import { PropsWithChildren } from 'react';

export const metadata = {
  title: 'Welcome to archiver',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
